### ISSUE TITLE
Doesn't work properly for names with degrees

### ISSUE THREAD

**Issue by TomThak** [joshfraser/PHP-Name-Parser#16]
Hello,
if I use it for parsing names with education degrees it doesnt work.

For example: 

"Ing. Jan Novák Csc."

**Comment by atla5** [comment]
@TomThak do you know where I could find a listing of 'Ing.' and 'Csc.' -style "education degrees" or could you otherwise provide one? I've not seen either of those before.

(just know about MD, PhD, Master, Prof.)

**Comment by TomThak** [comment]
Yes, it is Czech Republic, Slovakia degrees.

https://cs.wikipedia.org/wiki/Akademick%C3%BD_titul

The 1st column of the 1st table means, all the degrees before name, the 2nd table 1st coll means titles after name (academical degrees).

**Comment by atla5** [comment]
@TomThak, @joshfraser: I just completed and sent along a suggested addition to [parser.php](https://github.com/joshfraser/PHP-Name-Parser/blob/master/parser.php) for a bunch of those other prefixes.

I took the new items from [eric willis's listing](http://notes.ericwillis.com/2009/11/common-name-prefixes-titles-and-honorifics/) that I found online, and from the [wikipedia article](https://cs.wikipedia.org/wiki/Akademick%C3%BD_titul) TomThak provided. 

@TomThak since the english version of the article had different content and phrasing, I had to run the czech version through google translate. if you would look through my suggested edit and check that there aren't any mistakes, I'd appreciate it. 

@joshfraser not knowing how you wanted to document the changes to the file, I added a brief description to the class header that you can feel free to re/move if desired.

**Comment by joshfraser** [comment]
thanks everyone for getting this done.  merged.
